# Generated by Django 4.0.4 on 2022-04-11 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal', models.TextField()),
                ('pilihan_a', models.CharField(max_length=200)),
                ('pilihan_b', models.CharField(max_length=200)),
                ('pilihan_c', models.CharField(max_length=200)),
                ('pilihan_d', models.CharField(max_length=200)),
                ('kunci_jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Bank Soal',
            },
        ),
        migrations.CreateModel(
            name='LembarEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_evaluasi', models.CharField(max_length=10, unique=True)),
                ('nama_evaluasi', models.CharField(max_length=100)),
                ('jumlah_soal', models.IntegerField(default=2)),
                ('skor', models.IntegerField(default=4)),
                ('durasi', models.IntegerField(default=120)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif'), ('Selesai', 'Selesai')], default='Tidak Aktif', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Lembar Evaluasi',
            },
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.DateField()),
                ('no_hp', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Peserta',
            },
        ),
        migrations.CreateModel(
            name='NilaiPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_skor', models.IntegerField(null=True)),
                ('total_nilai', models.FloatField(default=0, null=True)),
                ('lembar_evaluasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi_harian.lembarevaluasi')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi_harian.peserta')),
            ],
            options={
                'verbose_name_plural': 'Nilai Peserta',
            },
        ),
        migrations.CreateModel(
            name='HasilEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=1)),
                ('is_true', models.BooleanField()),
                ('skor', models.IntegerField(default=0)),
                ('waktu_pengerjaan', models.DateTimeField(auto_now_add=True)),
                ('bank_soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi_harian.banksoal')),
                ('lembar_evaluasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi_harian.lembarevaluasi')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi_harian.peserta')),
            ],
            options={
                'verbose_name_plural': 'Hasil Evaluasi',
            },
        ),
        migrations.AddField(
            model_name='banksoal',
            name='lembar_evaluasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluasi_harian.lembarevaluasi'),
        ),
    ]
