# Generated by Django 4.0.4 on 2022-04-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi_harian', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NilaiPeserta',
            new_name='NilaiEvaluasi',
        ),
        migrations.AlterModelOptions(
            name='nilaievaluasi',
            options={'verbose_name_plural': 'Nilai Evaluasi'},
        ),
        migrations.RenameField(
            model_name='nilaievaluasi',
            old_name='total_nilai',
            new_name='total_nilai_evaluasi',
        ),
    ]
