# Generated by Django 4.0.4 on 2022-04-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi_harian', '0004_nilaiakhir_delete_totalnilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaiakhir',
            name='predikat',
            field=models.CharField(choices=[('Mumtaz Murtafi', 'Mumtaz Murtafi'), ('Mumtaz', 'Mumtaz'), ('Jayyid Jiddan', 'Jayyid Jiddan'), ('Jayyid', 'Jayyid'), ('Maqbul', 'Maqbul'), ('Rasib', 'Rasib'), ('Ghayyib', 'Ghayyib')], default='Ghayyib', max_length=50),
        ),
    ]
