# Generated by Django 4.0.4 on 2022-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi_harian', '0005_alter_nilaiakhir_predikat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaiakhir',
            name='predikat',
            field=models.CharField(choices=[('100', 'Mumtaz Murtafi'), ('90-99', 'Mumtaz'), ('80-89', 'Jayyid Jiddan'), ('70-79', 'Jayyid'), ('50-69', 'Maqbul'), ('1-49', 'Rasib'), ('0', 'Ghayyib')], default='Ghayyib', max_length=50),
        ),
    ]
